# Generated by Django 5.0 on 2025-04-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='notification_time',
            field=models.TimeField(default='09:00'),
        ),
    ]
